services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "443:443"
    volumes:
      - /mnt/hgfs/www:/var/www/html
    depends_on:
      - php
      - php74
    networks: 
      - appnet

  php:
    container_name: php82
    build:
      context: ./php
    volumes:
      - /mnt/hgfs/www:/var/www/html
      - ./php/php.ini:/etc/php/8.2/fpm/php.ini
    networks: 
      - appnet

  php74:
    container_name: php74
    build:
      context: ./php74
    volumes: 
      - /mnt/hgfs/www:/var/www/html
      - ./php74/php.ini:/usr/local/etc/php/php.ini
    networks:
      - appnet

  mysql:
    container_name: mysql8
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 123456
    volumes:
      - /mnt/hgfs/www:/www
      - mysql_data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/my.cnf
      # - ./mysql/mysqld.cnf:/etc/mysql/conf.d/my.cnf
    #  - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: [
    #   "--skip-chown"  # 关键：禁止容器修改文件所有权
    # ]
    ports:
      - "3306:3306"
    networks: 
      - appnet

  redis:
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  mongo:
    container_name: mongo
    build: ./mongo
    ports:
      - "27017:27017"
    environment:
      # 如果在这里创建了root 在init-mongo.js就不要重复创建了
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tb_migration_prod
    command: ["mongod", "--replSet", "tb-migration", "--keyFile", "/etc/mongo-keyfile"] # 添加了 command: ["mongod", "--replSet", "tb-migration"] 表示启动时以副本集名 tb-migration 启动。
    volumes:
      - mongo_data:/data/db
      # 如果你有初始化脚本可以加上这一行：
      # - ./mongo/mongo-keyfile:/etc/mongo-keyfile:ro
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    networks:
      - appnet
    entrypoint: ["/usr/local/bin/custom-entrypoint.sh"]
  
volumes:
  mysql_data:
  mongo_data:

networks:
  appnet:

# /etc/fstab
# .host:/data/mysql /mnt/hgfs/data/mysql vmhgfs defaults,uid=999,gid=999,fmask=007,dmask=007 0 0
# docker run --name mysql8 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=test -e MYSQL_USER=appuser -e MYSQL_PASSWORD=123456 -v /data/mysql:/var/lib/mysql -v ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql mysql:8.0.26
